baseurl = "https://yufablog.com"
title = "Yufa's Blog"
author = "@JeffProd"
copyright = "Copyright © 2008–2018, @JeffProd"
canonifyurls = true
paginate = 5

theme = "hugo-blog-jeffprod"

[taxonomies]
    tag = "tags"
    archive = "archives"
